services:
  web:
    image: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile
    ports:
      - 8080:8080
    environment:
      OTEL_EXPORTER_OTLP_PROTOCOL: grpc
      OTEL_EXPORTER_OTLP_ENDPOINT: http://dotnet-aspire-dashboard:18889
    depends_on:
      - dotnet-aspire-dashboard
  
  dotnet-aspire-dashboard:
    image: mcr.microsoft.com/dotnet/aspire-dashboard:9.0
    ports:
      - 18888:18888
    environment:
      DOTNET_DASHBOARD_UNSECURED_ALLOW_ANONYMOUS: true
      DOTNET_DASHBOARD_OTLP_ENDPOINT_URL: http://*:18889
